{
    "path": "api/individuals",
    "method": "GET",
    "ga4gh_passport_v1": [
        {
            "ga4gh_visa_v1": {
                "type": "ControlledAccessGrants",
                "value": {
                    "dataset123": {
                        "access": "4"
                    },
                    "dataset1123": {
                        "access": "4"
                    }
                }
            }
        }
    ]
}